# -*- coding: utf-8 -*-
{
    'name': "Theme Alan",
    'category': 'Theme/eCommerce',
    'version': '1.9',
    'license': 'OPL-1',
    'author': 'Atharva System',
    'support': 'support@atharvasystem.com',
    'website' : 'https://www.atharvasystem.com',
    'live_test_url': 'https://alan-v17.atharvasystem.com',
    'description': """Theme Alan is one of the most powerful, amazing and flexible theme on Odoo store.""",
    'summary': 'Theme Alan is one of the most powerful, amazing and flexible theme on Odoo store.',
    'depends': ['atharva_theme_base'],
    'data': [
        'data/product_queries_mail.xml',
        'views/headers_footers/header.xml',
        'views/headers_footers/footer.xml',
        'views/headers_footers/options.xml',
        'views/shop/shop.xml',
        'views/shop/templates.xml',
        'views/mixins.xml',
        'views/product/product.xml',
        'views/snippets/s_img_hotspot.xml',
        'views/snippets/snippets.xml',
        'views/snippets/s_website_builder.xml',
        'views/res_config_setting.xml',

        # Frame Builder
        'views/snippets/s_blog_slider.xml',
        'views/snippets/s_brand_product.xml',
        'views/snippets/s_brand_slider.xml',
        'views/snippets/s_category_product.xml',
        'views/snippets/s_category_slider.xml',
        'views/snippets/s_dynamic.xml',
        'views/snippets/s_product_banner.xml',
        'views/snippets/s_product_slider.xml',
        'views/snippets/s_megamenu.xml'
    ],
    'assets': {
        'web._assets_primary_variables': [
            '/theme_alan/static/src/scss/base/*',
        ],
        'web.assets_frontend': [
            '/theme_alan/static/src/js/frontend/**/*.js',
            '/theme_alan/static/src/js/snippets/Hotspot/000.js',
            '/theme_alan/static/src/xml/templates.xml',
            '/theme_alan/static/src/scss/feather/*',
            '/theme_alan/static/src/scss/general/*',
            '/theme_alan/static/src/scss/dynamic/*',
            '/theme_alan/static/src/scss/dynamic/advance-megamenu/*',
            '/theme_alan/static/src/scss/product-details/*',
            '/theme_alan/static/src/scss/shop/*',
            '/theme_alan/static/src/scss/header/*',
            '/theme_alan/static/src/scss/footer/*',
            '/theme_alan/static/src/documentation/*',
        ],
        'web._assets_frontend_helpers': [],
        'web.assets_backend': [
            '/theme_alan/static/src/scss/dynamic/*',
            '/theme_alan/static/src/scss/dynamic/advance-megamenu/*',
            '/theme_alan/static/src/scss/feather/*',
            '/theme_alan/static/src/scss/backend.scss',
        ],
        'website.assets_editor':[
            '/theme_alan/static/src/js/AlanTouch/*',
            '/theme_alan/static/src/js/components/Menus/*'
        ],
        'website.assets_wysiwyg':[
            '/theme_alan/static/src/js/snippets/Hotspot/options.js',
            '/theme_alan/static/src/xml/templates.xml',
            '/theme_alan/static/src/xml/website_builder/*.xml',
            '/theme_alan/static/src/xml/website_builder/**/*.xml',
            '/theme_alan/static/src/js/snippets/WebsiteBuilder/*',
            # Frame Builder
            '/theme_alan/static/src/xml/frame_static_snippets/**/*',
            '/theme_alan/static/src/xml/mixins/*',
            '/theme_alan/static/src/js/frontend/base/mixins.js',
            '/theme_alan/static/src/js/frontend/registries.js',
            '/theme_alan/static/src/js/components/UserInfo/*',
            '/theme_alan/static/src/js/snippets/DynamicSnippets/**/*',
            '/theme_alan/static/src/js/snippets/StaticSnippets/*',
            '/theme_alan/static/src/js/components/SelectData/*',
            '/theme_alan/static/src/js/snippets/Megamenu/**/*',
            '/theme_alan/static/src/js/components/SnippetPicker/*',
            '/theme_alan/static/src/js/components/SnippetBox/*',
            '/theme_alan/static/src/js/components/FramePreview/*',
            '/theme_alan/static/src/js/components/FrameData/*',
            '/theme_alan/static/src/js/components/FrameMaker/*',
            '/theme_alan/static/src/js/components/SnippetBuilder/*',
            '/theme_alan/static/src/js/snippet_config.js',

        ],
    },
    'price': 222.00,
    'currency': 'EUR',
    'images': ['static/description/alan_description.jpg','static/description/alan_screenshot.gif'],
    'application': False,
}
